### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by gaiterjones** [datendampfer/magento2-paypal-plus#1]
Testing this with Magento 2.3.1 / PHP 7.2 getting an exception error when trying to checkout in frontend

`Exception #0 (InvalidArgumentException): Plugin class Iways\PayPalPlus\Plugin\Payment\Model\MethodListPlugin doesn't exist`

First time I have tried using this module with Magento 2 so not sure if I have a config problem or there is a module problem with 2.3.1 - have you tested your fork?

**Comment by codedge** [comment]
What version do you use? Latest 0.3.4?
This error has been fixed in 0.3.4

**Comment by gaiterjones** [comment]
Yes it is 0.3.4 reinstalled just now in a fresh magento2 - the error is still there.

**Comment by gaiterjones** [comment]
Fixed with iways 1.2.3 release.
